######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 27 12:10:24 2015
######################################################################
QT       += core gui widgets

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = assgn2
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ImageWidget.h \
    PreviewViewer.h
SOURCES +=  main.cpp ImageWidget.cpp\
    PreviewViewer.cpp
